#!/bin/bash

# Compile the Swift files into an executable
swiftc main.swift Math/Mesh.swift Math/Vector.swift Objects/Cube.swift Objects/Diamond.swift Objects/Icosphere.swift Objects/Pyramid.swift Objects/Torus.swift Objects/MobiusStrip.swift Objects/Wave.swift Objects/Helix.swift Renderer/Renderer.swift Transform/transform.swift -o app

echo "Compiling done!"
